name: Build Test

on:
  push:

jobs:

  build_test:
    runs-on: ubuntu-22.04
    container: 
      image: ubuntu:22.04
    arch: x64
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: actions/checkout@v6
      - name: Setup Flutter
        run: |
          cd "$GITHUB_WORKSPACE"
          apt update
          apt install -y cmake ninja-build clang pkg-config libgtk-3-dev build-essential
          git clone https://github.com/flutter/flutter.git -b stable
          export PATH="$GITHUB_WORKSPACE/flutter/bin:$PATH"
          export PATH="$GITHUB_WORKSPACE/flutter/bin/cache/dart-sdk/bin:$PATH"
          echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH
          echo "$GITHUB_WORKSPACE/flutter/bin/cache/dart-sdk/bin" >> $GITHUB_PATH
          flutter --version
          flutter doctor
      - name: Build Flutter
        run: |
          apt update
          apt install libsecret-1-dev libmpv-dev -y
          cd "$GITHUB_WORKSPACE"
          flutter pub get
          flutter build linux --debug
              '