name: Build Test

on:
  push:

jobs:

  build_test:
    runs-on: codeberg-x86
    container: 
      image: ubuntu:24.04
    steps:
      - name: Setup Node
        run: |
          export DEBIAN_FRONTEND=noninteractive
          ln -fs /usr/share/zoneinfo/UTC /etc/localtime
          apt update
          apt install -y tzdata
          dpkg-reconfigure --frontend noninteractive tzdata
          apt install -y curl
          curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
          apt install -y nodejs
          node -v
          npm -v
      - uses: actions/checkout@v6
      - name: Setup Flutter
        run: |
          cd "$GITHUB_WORKSPACE"
          apt update
          apt install -y cmake ninja-build clang pkg-config libgtk-3-dev build-essential unzip libmpv-dev libasound2-dev libsecret-1-dev git
          git clone https://github.com/flutter/flutter.git -b stable
          export PATH="$GITHUB_WORKSPACE/flutter/bin:$PATH"
          export PATH="$GITHUB_WORKSPACE/flutter/bin/cache/dart-sdk/bin:$PATH"
          echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH
          echo "$GITHUB_WORKSPACE/flutter/bin/cache/dart-sdk/bin" >> $GITHUB_PATH
          flutter --version
          flutter doctor
      - name: Build Flutter
        run: |
          apt update
          apt install libsecret-1-dev libmpv-dev lld -y
          cd "$GITHUB_WORKSPACE"
          flutter pub get
          flutter build linux --debug
