name: build-test

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: nix
    steps:
      - name: Install Node.js
        run: nix-env -iA nixpkgs.nodejs

      - name: Checkout repository
        uses: https://github.com/actions/checkout@v3

      - name: Build Flutter app in devShell
        run: |
          NIX_DOWNLOAD_BUFFER_SIZE=10485760 \
          nix --extra-experimental-features "nix-command flakes" develop --command bash -c '
            flutter config --enable-linux-desktop
            flutter pub get
            flutter build linux --release
            ls -lh build/linux/x64/release/bundle
          '
